### ISSUE TITLE
Schematics error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by ruslanguns** [nestjs/schematics#378]
## Current behavior

If you generate a module with `nest g mo core/module` in order to have a module called DatabaseModule into your CoreModule then throws  an error like: 

```bash
TypeError: Cannot read property 'length' of undefined
    at MetadataManager.insertSymbolToMetadata (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\dist\utils\metadata.manager.js:104:33)
    at MetadataManager.insert (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\dist\utils\metadata.manager.js:41:25)
    at ModuleMetadataDeclarator.declare (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\dist\utils\module-metadata.declarator.js:7:34)
    at ModuleDeclarator.declare (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\dist\utils\module.declarator.js:14:33)
    at G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\dist\lib\module\module.factory.js:53:51
    at MergeMapSubscriber.project (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\node_modules\@angular-devkit\schematics\src\rules\call.js:74:24)       
    at MergeMapSubscriber._tryNext (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (G:\mis-cursos\quiz-api\node_modules\@nestjs\schematics\node_modules\rxjs\internal\operators\mergeMap.js:92:26)

Failed to execute command: "G:\mis-cursos\quiz-api\node_modules\@nestjs\cli\node_modules\.bin\schematics" @nestjs/schematics:module --name=core/database --no-dry-run --collection="@nestjs/schematics" --language="ts" --sourceRoot="src" --spec
```
## Possible Solution

The work around is creating it manually. 
## Environment

<pre><code>
Nest version: X.Y.Z

 
```bash
➜  quiz-api git:(master) nest info

 _   _             _      ___  _____  _____  _     _____ 
| \ | |           | |    |_  |/  ___|/  __ \| |   |_   _|
|  \| |  ___  ___ | |_     | |\ `--. | /  \/| |     | |  
| . ` | / _ \/ __|| __|    | | `--. \| |    | |     | |  
| |\  ||  __/\__ \| |_ /\__/ //\__/ /| \__/\| |_____| |_ 
\_| \_/ \___||___/ \__|\____/ \____/  \____/\_____/\___/ 


[System Information]
OS Version     : Windows 10
NodeJS Version : v12.16.2
YARN Version    : 1.22.4 

[Nest CLI]
Nest CLI Version : 7.1.5        

[Nest Platform Information]     
platform-express version : 7.0.9
mongoose version         : 6.4.0
common version           : 7.0.9
config version           : 0.4.0
core version             : 7.0.9
```

Others:

</code></pre>

**Comment by kamilmysliwiec** [comment]
Please provide a minimum reproduction repository.

**Comment by ruslanguns** [comment]
This issue happened on upgrade, then after deleting node_modules directory it has dissapeared. Just noticed of that. Clossing the issue.

**Comment by docred-latam** [comment]
I'm afraid I'm getting the same error. 
I tried removing `dist` and `node_modules` with no success.
Here my versions:
```
"@nestjs/cli": "^7.4.1",
"@nestjs/schematics": "^7.0.1",
"@nestjs/testing": "^7.2.0",
"@nestjs/common": "7.2.0",
"@nestjs/config": "0.5.0",
"@nestjs/core": "7.2.0",
"@nestjs/graphql": "7.4.6",
"@nestjs/passport": "7.1.0",
"@nestjs/platform-express": "7.2.0",
"@nestjs/schedule": "0.4.0",
"@nestjs/swagger": "4.5.12",
"@nestjs/typeorm": "7.1.0",
```

It started happening several versions ago but can't remember exactly which.

What other information can I provide to aid in the resolution of this issue?

**Comment by tritoanst** [comment]
I think your 'app.module.ts' (or 'libName.module.ts') edited.
```javascript
@Module({
  imports: allModules,
  providers: [AppService],
})
export class AppModule {}
```
update with:
```javascript
@Module({
  imports: [
    ...allModules,
  ],
  providers: [AppService],
})
export class AppModule {}
```

**Comment by heavenkiller2018** [comment]
I have the same problem . when i use cli to create a new module:
`nest g mo auth`

error statck is the following:
```
TypeError: Cannot read property 'properties' of undefined
    at MetadataManager.insert (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@nestjs\schematics\dist\utils\metadata.manager.js:13:41)    at ModuleMetadataDeclarator.declare (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@nestjs\schematics\dist\utils\module-metadata.declarator.js:8:34)
    at ModuleDeclarator.declare (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@nestjs\schematics\dist\utils\module.declarator.js:15:33)
    at C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@nestjs\schematics\dist\lib\module\module.factory.js:54:51
    at MergeMapSubscriber.project (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@nestjs\schematics\node_modules\@angular-devkit\schematics\src\rules\call.js:74:24)
    at MergeMapSubscriber._tryNext (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\rxjs\internal\Subscriber.js:66:18)
    at MergeMapSubscriber.notifyNext (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\rxjs\internal\operators\mergeMap.js:95:26)
    at InnerSubscriber._next (C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\rxjs\internal\InnerSubscriber.js:28:21)

Failed to execute command: "C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\@nestjs\cli\node_modules\.bin\schematics" @nestjs/schematics:module --name=authing --no-dry-run --collection="@nestjs/schematics" --language="ts" --sourceRoot="src" --spec
```

why? who can help to fix it?

**Comment by jfcmoeller** [comment]
I have the same issue. Did you find a solution?
